version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '3443:443'
    links:
      - backend
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://backend:3000'
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/myapp
